import React, {useEffect} from 'react';
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";
import {useRouter} from "next/router";
import NProgress from "nprogress";

function Layout({title = "MovieBook", children}) {
    const router = useRouter()
    useEffect(() => {
        router.events.on('routeChangeStart', url => {
            // console.log(url)
            NProgress.start()
        })
        router.events.on('routeChangeComplete', () => NProgress.done())
        router.events.on('routeChangeError', () => NProgress.done())
    })
    return (
        <React.Fragment>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by Roela Apps"/>
                <meta name="viewport"
                      content="width=device-width, initial-scale=1.0 ,maximum-scale=1.0, user-scalable=no,viewport-fit=cover"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="manifest" href="/manifest.json"/>
            </Head>
            <div className="content">
                <Navbar/>
                {children}
                <Footer/>
            </div>
        </React.Fragment>
    );
}

export default Layout;